name: Update Modrinth Description

on:
    workflow_call:
        inputs:
            project_id:
                required: true
                type: string
            file:
                required: false
                default: "README.md"
                type: string
        secrets:
            MODRINTH_TOKEN:
                required: true

jobs:
    update-description:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Update Modrinth project description
            env:
                MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
            run: |
                set -e

                echo "Preparing description payload..."
                jq -Rs '{ body: . }' < "${{ inputs.file }}" > body.json

                echo "Sending PATCH request to Modrinth..."
                response=$(curl -s -w "\n%{http_code}" -X PATCH https://api.modrinth.com/v2/project/${{ inputs.project_id }} \
                    -H "Authorization: $MODRINTH_TOKEN" \
                    -H "Content-Type: application/json" \
                    --data @body.json)

                body=$(echo "$response" | head -n -1)
                status=$(echo "$response" | tail -n 1)

                echo "Response Status: $status"

                if [[ "$status" -ge 200 && "$status" -lt 300 ]]; then
                    echo "✅ Successfully updated Modrinth project description!"
                else
                    echo "❌ Failed to update description (status $status)"
                    if command -v jq &> /dev/null; then
                        echo "$body" | jq
                    else
                        echo "$body"
                    fi
                    exit 1
                fi
